baseURL: "https://rodrigosoares.netlify.app/"
languageCode: en-us
title: Rodrigo Soares
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    #- identifier: notes
    # name: Notes
    #  url: https://notes.arkalim.org
    #  weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Rodrigo Soares"
    subtitle: Incoming [**Web Programmer**](https://imdfic.imd.ufrn.br/index) at the **University of Rio Grande Do Norte** and Software Engineer 🧑🏻‍💻 at [**Estácio de Sá University**](https://estacio.br/cursos/graduacao/engenharia-de-software). <br><br> If you want to know me better, I suggest you explore this clean and simple site. <br>You can start by clicking the **links above** or accessing my **social media**. You can also send an **e-mail** using the icons below. 
    imageUrl: "home/me.jpg"
    imageWidth: 180
    imageHeight: 180
  #   buttons:
  #     - name: Resume
  #     url: "https://drive.google.com/file/d/15bupi_Ez5GhhNa2LIT7an1Qxg-0XKYH2/view"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:rodrigoseal@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/rodrigo-soares-93124041/"
    - name: "github"
      url: "https://github.com/RodrigoHSoares"
  #  - name: "youtube"
   #   url: ""
    - name: "cv"
      url: ""


  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
