backend:
  name: git-gateway
  repo: Portifolio
  branch:  wip-insert-some-contents 

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}